/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// taskParser.ts
async function getAllTasks(app, queryPaths) {
  const files = getQueryFiles(app, queryPaths);
  const tasks = [];
  for (const file of files) {
    const content = await app.vault.read(file);
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const parsed = parseTaskLine(line, file.path, i);
      if (parsed) {
        tasks.push(parsed);
      }
    }
  }
  return tasks;
}
function getQueryFiles(app, queryPaths) {
  const enabledPaths = queryPaths.filter((p) => p.enabled).map((p) => p.path);
  if (enabledPaths.length === 0)
    return app.vault.getMarkdownFiles();
  const allFiles = app.vault.getMarkdownFiles();
  const result = [];
  for (const file of allFiles) {
    for (const qp of enabledPaths) {
      if (qp === "") {
        result.push(file);
        break;
      }
      const prefix = qp.endsWith("/") ? qp : qp + "/";
      if (file.path === qp || file.path.startsWith(prefix)) {
        result.push(file);
        break;
      }
    }
  }
  return result;
}
function parseTaskLine(line, filePath, lineNumber) {
  const taskMatch = line.match(/^\s*-\s*\[([ xX])\]\s+(.*)$/);
  if (!taskMatch)
    return null;
  const completed = taskMatch[1].toLowerCase() === "x";
  const rest = taskMatch[2];
  const startDate = extractDate(rest, "\u{1F6EB}");
  const dueDate = extractDate(rest, "\u{1F4C5}");
  if (!startDate && !dueDate)
    return null;
  const finalStart = startDate || dueDate;
  const finalDue = dueDate || startDate;
  const priority = extractPriority(rest);
  const tags = extractTags(rest);
  let description = cleanDescription(rest);
  return {
    id: `${filePath}#${lineNumber}`,
    description,
    completed,
    filePath,
    lineNumber,
    startDate: finalStart,
    dueDate: finalDue,
    priority,
    tags,
    rawText: line
  };
}
function extractDate(text, emoji) {
  const regex = new RegExp(
    `${escapeRegex(emoji)}\\s*(\\d{4}-\\d{2}-\\d{2})`
  );
  const match = text.match(regex);
  if (match) {
    const dateStr = match[1];
    const d = new Date(dateStr);
    if (!isNaN(d.getTime())) {
      return dateStr;
    }
  }
  return void 0;
}
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function extractPriority(text) {
  const match = text.match(/❗{1,3}/);
  if (!match)
    return "none";
  const count = match[0].length;
  if (count >= 3)
    return "high";
  if (count === 2)
    return "medium";
  return "low";
}
function extractTags(text) {
  const tags = [];
  const regex = /#([\w-]+)/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    tags.push(match[1]);
  }
  return tags;
}
function cleanDescription(text) {
  let desc = text;
  desc = desc.replace(/🛫\s*\d{4}-\d{2}-\d{2}/g, "");
  desc = desc.replace(/📅\s*\d{4}-\d{2}-\d{2}/g, "");
  desc = desc.replace(/⏳\s*\d{4}-\d{2}-\d{2}/g, "");
  desc = desc.replace(/✅\s*\d{4}-\d{2}-\d{2}/g, "");
  desc = desc.replace(/❗{1,3}/g, "");
  desc = desc.replace(/#[\w-]+/g, "");
  desc = desc.trim().replace(/\s+/g, " ");
  return desc;
}
function groupTasksByDate(tasks) {
  const map = /* @__PURE__ */ new Map();
  for (const task of tasks) {
    if (!task.startDate)
      continue;
    const start = task.startDate;
    const end = task.dueDate || start;
    const dates = getDateRange(start, end);
    for (const dateStr of dates) {
      if (!map.has(dateStr)) {
        map.set(dateStr, []);
      }
      map.get(dateStr).push(task);
    }
  }
  return map;
}
function getDateRange(start, end) {
  const result = [];
  const s = new Date(start);
  const e = new Date(end);
  if (s > e) {
    return [start];
  }
  const current = new Date(s);
  while (current <= e) {
    result.push(formatDateStr(current));
    current.setDate(current.getDate() + 1);
  }
  return result;
}
function formatDateStr(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function isMultiDayTask(task) {
  if (!task.startDate || !task.dueDate)
    return false;
  return task.startDate !== task.dueDate;
}
async function updateTaskDates(app, task, newStartDate, newDueDate) {
  const file = app.vault.getAbstractFileByPath(task.filePath);
  if (!(file instanceof import_obsidian.TFile))
    return;
  const content = await app.vault.read(file);
  const lines = content.split("\n");
  if (task.lineNumber < 0 || task.lineNumber >= lines.length)
    return;
  let line = lines[task.lineNumber];
  if (line.includes("\u{1F6EB}")) {
    line = line.replace(/🛫\s*\d{4}-\d{2}-\d{2}/, `\u{1F6EB} ${newStartDate}`);
  } else {
    line += ` \u{1F6EB} ${newStartDate}`;
  }
  if (line.includes("\u{1F4C5}")) {
    line = line.replace(/📅\s*\d{4}-\d{2}-\d{2}/, `\u{1F4C5} ${newDueDate}`);
  } else {
    line += ` \u{1F4C5} ${newDueDate}`;
  }
  lines[task.lineNumber] = line;
  await app.vault.modify(file, lines.join("\n"));
}
function shiftTaskDates(task, days) {
  const newStart = addDays(task.startDate || "", days);
  const newDue = addDays(task.dueDate || task.startDate || "", days);
  return { startDate: newStart, dueDate: newDue };
}
function addDays(dateStr, days) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return formatDateStr(d);
}
var import_obsidian;
var init_taskParser = __esm({
  "taskParser.ts"() {
    import_obsidian = require("obsidian");
  }
});

// settings.ts
var DEFAULT_SETTINGS, PRESET_COLORS;
var init_settings = __esm({
  "settings.ts"() {
    DEFAULT_SETTINGS = {
      colorRules: [],
      filterRules: [],
      projects: [],
      queryPaths: [
        { id: "default", path: "", enabled: true }
      ]
    };
    PRESET_COLORS = [
      "#e6194b",
      "#f58231",
      "#ffe119",
      "#bfef45",
      "#3cb44b",
      "#42d4f4",
      "#4363d8",
      "#911eb4",
      "#f032e6",
      "#a9a9a9",
      "#fabed4",
      "#ffd8b1",
      "#fffac8",
      "#aaffc3",
      "#e6beff",
      "#808000",
      "#ffcccc",
      "#ffe0b2",
      "#fff9c4",
      "#c8e6c9"
    ];
  }
});

// colorRulesModal.ts
var import_obsidian2, DISPLAY_MODE_LABEL, PROPERTY_LABELS, ColorRulesModal;
var init_colorRulesModal = __esm({
  "colorRulesModal.ts"() {
    import_obsidian2 = require("obsidian");
    init_settings();
    DISPLAY_MODE_LABEL = {
      bar: "\u6807\u7B7E\u6761",
      block: "\u6574\u5757"
    };
    PROPERTY_LABELS = {
      tags: "\u6807\u7B7E",
      priority: "\u4F18\u5148\u7EA7",
      description: "\u63CF\u8FF0"
    };
    ColorRulesModal = class extends import_obsidian2.Modal {
      constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
        this.rules = plugin.settings.colorRules.map((r) => ({ ...r }));
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("color-rules-modal");
        contentEl.createEl("h3", { text: "\u5206\u7C7B\u914D\u8272" });
        contentEl.createEl("div", {
          cls: "modal-helper-text",
          text: "\u6807\u7B7E\uFF1A\u586B\u5199\u6807\u7B7E\u540D\uFF08\u4E0D\u542B#\uFF09\uFF0C\u5982 \u5DE5\u4F5C\u3001\u6570\u5B66\u3002\u4F18\u5148\u7EA7\uFF1A\u586B\u5199 high / medium / low / none\u3002\u63CF\u8FF0\uFF1A\u586B\u5199\u5173\u952E\u8BCD\u5339\u914D\u4EFB\u52A1\u6587\u672C\u3002"
        });
        this.contentArea = contentEl.createDiv({ cls: "color-rules-list" });
        this.renderRuleList();
        const addBtn = contentEl.createEl("button", {
          cls: "color-rules-add-btn",
          text: "+ \u65B0\u589E\u89C4\u5219"
        });
        addBtn.addEventListener("click", () => this.addRule());
        const footer = contentEl.createDiv({ cls: "color-rules-footer" });
        const cancelBtn = footer.createEl("button", { text: "\u53D6\u6D88" });
        cancelBtn.addEventListener("click", () => this.close());
        const saveBtn = footer.createEl("button", {
          cls: "mod-cta",
          text: "\u5B8C\u6210"
        });
        saveBtn.addEventListener("click", () => {
          this.plugin.settings.colorRules = this.rules.filter(
            (r) => r.keyword.trim()
          );
          this.plugin.saveSettings();
          this.close();
        });
      }
      onClose() {
        const { contentEl } = this;
        contentEl.empty();
      }
      renderRuleList() {
        this.contentArea.empty();
        if (this.rules.length === 0) {
          this.contentArea.createDiv({
            cls: "color-rules-empty",
            text: "\u6682\u65E0\u89C4\u5219\uFF0C\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u65B0\u589E"
          });
          return;
        }
        for (let i = 0; i < this.rules.length; i++) {
          const rule = this.rules[i];
          const row = this.contentArea.createDiv({ cls: "color-rule-row" });
          const colorSwatch = row.createDiv({ cls: "color-rule-swatch" });
          colorSwatch.style.backgroundColor = rule.color;
          colorSwatch.addEventListener("click", (e) => {
            e.stopPropagation();
            this.showColorPicker(colorSwatch, rule);
          });
          const propSelect = row.createEl("select", { cls: "color-rule-field" });
          for (const [value, label] of Object.entries(PROPERTY_LABELS)) {
            propSelect.createEl("option", { text: label, value });
          }
          propSelect.value = rule.property;
          propSelect.addEventListener("change", () => {
            rule.property = propSelect.value;
          });
          row.createSpan({ cls: "color-rule-eq", text: "=" });
          const keywordInput = row.createEl("input", {
            cls: "color-rule-keyword",
            type: "text",
            value: rule.keyword,
            attr: { placeholder: "\u5173\u952E\u8BCD" }
          });
          keywordInput.addEventListener("input", () => {
            rule.keyword = keywordInput.value;
          });
          const modeBtn = row.createEl("button", {
            cls: "color-rule-mode-btn",
            text: DISPLAY_MODE_LABEL[rule.displayMode]
          });
          modeBtn.addEventListener("click", () => {
            rule.displayMode = rule.displayMode === "bar" ? "block" : "bar";
            modeBtn.setText(DISPLAY_MODE_LABEL[rule.displayMode]);
          });
          const toggleWrapper = row.createDiv({ cls: "color-rule-toggle" });
          const toggle = toggleWrapper.createEl("input", {
            type: "checkbox",
            attr: { id: `rule-toggle-${i}` }
          });
          toggle.checked = rule.enabled;
          toggle.addEventListener("change", () => {
            rule.enabled = toggle.checked;
          });
          const deleteBtn = row.createEl("button", {
            cls: "color-rule-delete",
            text: "\xD7"
          });
          deleteBtn.addEventListener("click", () => {
            this.rules.splice(i, 1);
            this.renderRuleList();
          });
        }
      }
      addRule() {
        this.rules.push({
          id: crypto.randomUUID(),
          color: PRESET_COLORS[this.rules.length % PRESET_COLORS.length],
          property: "tags",
          keyword: "",
          enabled: true,
          displayMode: "bar"
        });
        this.renderRuleList();
      }
      showColorPicker(anchor, rule) {
        const existing = document.querySelector(".color-picker-popover");
        if (existing)
          existing.remove();
        const popover = document.body.createDiv({ cls: "color-picker-popover" });
        const grid1 = popover.createDiv({ cls: "color-picker-grid" });
        for (const c of PRESET_COLORS.slice(0, 16)) {
          const swatch = grid1.createDiv({ cls: "color-picker-swatch" });
          swatch.style.backgroundColor = c;
          if (c === rule.color)
            swatch.addClass("selected");
          swatch.addEventListener("click", (e) => {
            e.stopPropagation();
            rule.color = c;
            anchor.style.backgroundColor = c;
            popover.remove();
            this.renderRuleList();
          });
        }
        const sep = popover.createDiv({ cls: "color-picker-sep", text: "\u6574\u5757\u5E95\u8272\u63A8\u8350" });
        const grid2 = popover.createDiv({ cls: "color-picker-grid" });
        for (const c of PRESET_COLORS.slice(16)) {
          const swatch = grid2.createDiv({ cls: "color-picker-swatch" });
          swatch.style.backgroundColor = c;
          if (c === rule.color)
            swatch.addClass("selected");
          swatch.addEventListener("click", (e) => {
            e.stopPropagation();
            rule.color = c;
            anchor.style.backgroundColor = c;
            popover.remove();
            this.renderRuleList();
          });
        }
        const closeHandler = (e) => {
          if (!popover.contains(e.target) && e.target !== anchor) {
            popover.remove();
            document.removeEventListener("click", closeHandler);
            this.renderRuleList();
          }
        };
        setTimeout(() => {
          document.addEventListener("click", closeHandler);
        }, 0);
        const rect = anchor.getBoundingClientRect();
        popover.style.position = "fixed";
        popover.style.top = `${rect.bottom + 4}px`;
        popover.style.left = `${Math.min(rect.left, window.innerWidth - 240)}px`;
        popover.style.zIndex = "1000";
      }
    };
  }
});

// filterModal.ts
var import_obsidian3, PROPERTY_LABELS2, FilterModal;
var init_filterModal = __esm({
  "filterModal.ts"() {
    import_obsidian3 = require("obsidian");
    PROPERTY_LABELS2 = {
      tags: "\u6807\u7B7E",
      priority: "\u4F18\u5148\u7EA7",
      description: "\u63CF\u8FF0"
    };
    FilterModal = class extends import_obsidian3.Modal {
      constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
        this.rules = plugin.settings.filterRules.map((r) => ({ ...r }));
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("filter-modal");
        contentEl.createEl("h3", { text: "\u7B5B\u9009\u6392\u9664" });
        contentEl.createEl("div", {
          cls: "modal-helper-text",
          text: "\u6807\u7B7E\uFF1A\u586B\u5199\u6807\u7B7E\u540D\uFF08\u4E0D\u542B#\uFF09\uFF0C\u5982 \u5DE5\u4F5C\u3001\u6570\u5B66\u3002\u4F18\u5148\u7EA7\uFF1A\u586B\u5199 high / medium / low / none\u3002\u63CF\u8FF0\uFF1A\u586B\u5199\u5173\u952E\u8BCD\u5339\u914D\u4EFB\u52A1\u6587\u672C\u3002"
        });
        this.contentArea = contentEl.createDiv({ cls: "filter-rules-list" });
        this.renderRuleList();
        const addBtn = contentEl.createEl("button", {
          cls: "filter-add-btn",
          text: "+ \u65B0\u589E\u7B5B\u9009"
        });
        addBtn.addEventListener("click", () => this.addRule());
        const footer = contentEl.createDiv({ cls: "filter-footer" });
        const cancelBtn = footer.createEl("button", { text: "\u53D6\u6D88" });
        cancelBtn.addEventListener("click", () => this.close());
        const saveBtn = footer.createEl("button", {
          cls: "mod-cta",
          text: "\u5B8C\u6210"
        });
        saveBtn.addEventListener("click", () => {
          this.plugin.settings.filterRules = this.rules.filter(
            (r) => r.keyword.trim()
          );
          this.plugin.saveSettings();
          this.close();
        });
      }
      onClose() {
        const { contentEl } = this;
        contentEl.empty();
      }
      renderRuleList() {
        this.contentArea.empty();
        if (this.rules.length === 0) {
          this.contentArea.createDiv({
            cls: "filter-rules-empty",
            text: "\u6682\u65E0\u7B5B\u9009\u89C4\u5219\uFF0C\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u65B0\u589E"
          });
          return;
        }
        for (let i = 0; i < this.rules.length; i++) {
          const rule = this.rules[i];
          const row = this.contentArea.createDiv({ cls: "filter-rule-row" });
          const selectWrapper = row.createDiv({ cls: "filter-select-wrap" });
          const select = selectWrapper.createEl("select", { cls: "filter-select" });
          for (const [value, label] of Object.entries(PROPERTY_LABELS2)) {
            select.createEl("option", { text: label, value });
          }
          select.value = rule.property;
          select.addEventListener("change", () => {
            rule.property = select.value;
          });
          row.createSpan({ cls: "filter-contains", text: "\u5305\u542B" });
          const keywordInput = row.createEl("input", {
            cls: "filter-keyword",
            type: "text",
            value: rule.keyword,
            attr: { placeholder: "\u5173\u952E\u8BCD" }
          });
          keywordInput.addEventListener("input", () => {
            rule.keyword = keywordInput.value;
          });
          const toggleWrapper = row.createDiv({ cls: "filter-toggle" });
          const toggle = toggleWrapper.createEl("input", {
            type: "checkbox",
            attr: { id: `filter-toggle-${i}` }
          });
          toggle.checked = rule.enabled;
          toggle.addEventListener("change", () => {
            rule.enabled = toggle.checked;
          });
          const deleteBtn = row.createEl("button", {
            cls: "filter-delete",
            text: "\xD7"
          });
          deleteBtn.addEventListener("click", () => {
            this.rules.splice(i, 1);
            this.renderRuleList();
          });
        }
      }
      addRule() {
        this.rules.push({
          id: crypto.randomUUID(),
          property: "tags",
          keyword: "",
          enabled: true
        });
        this.renderRuleList();
      }
    };
  }
});

// queryPathModal.ts
var import_obsidian4, QueryPathModal;
var init_queryPathModal = __esm({
  "queryPathModal.ts"() {
    import_obsidian4 = require("obsidian");
    QueryPathModal = class extends import_obsidian4.Modal {
      constructor(app, plugin, onSave) {
        super(app);
        this.plugin = plugin;
        this.onSave = onSave;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("query-path-modal");
        contentEl.createEl("h3", { text: "\u626B\u63CF\u8DEF\u5F84" });
        contentEl.createEl("p", {
          cls: "query-path-desc",
          text: "\u9009\u62E9\u8981\u626B\u63CF\u4EFB\u52A1\u7684\u6587\u4EF6\u5939\u6216\u6587\u4EF6\u3002\u9ED8\u8BA4\u626B\u63CF\u6240\u6709\u6587\u4EF6\u3002"
        });
        this.pathList = contentEl.createDiv({ cls: "query-path-list" });
        this.renderPathList();
        const addBtn = contentEl.createEl("button", {
          cls: "query-path-add-btn",
          text: "+ \u65B0\u589E\u8DEF\u5F84"
        });
        addBtn.addEventListener("click", () => this.addPath());
        const footer = contentEl.createDiv({ cls: "query-path-footer" });
        const cancelBtn = footer.createEl("button", { text: "\u53D6\u6D88" });
        cancelBtn.addEventListener("click", () => this.close());
        const saveBtn = footer.createEl("button", { cls: "mod-cta", text: "\u4FDD\u5B58" });
        saveBtn.addEventListener("click", () => {
          this.plugin.saveSettings().then(() => {
            this.onSave();
            this.close();
          });
        });
      }
      onClose() {
        const { contentEl } = this;
        contentEl.empty();
      }
      renderPathList() {
        this.pathList.empty();
        const paths = this.plugin.settings.queryPaths;
        if (paths.length === 0) {
          this.pathList.createDiv({
            cls: "query-path-empty",
            text: "\u6682\u65E0\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u626B\u63CF\u6240\u6709\u6587\u4EF6"
          });
          return;
        }
        const allFiles = this.app.vault.getAllLoadedFiles();
        const mdFiles = allFiles.filter((f) => f instanceof import_obsidian4.TFile && f.extension === "md");
        const folders = allFiles.filter((f) => f instanceof import_obsidian4.TFolder);
        const items = [
          { value: "", label: "(\u6240\u6709\u6587\u4EF6)" },
          ...folders.map((f) => ({ value: f.path, label: `\u{1F4C1} ${f.path}` })),
          ...mdFiles.map((f) => ({ value: f.path, label: `\u{1F4DD} ${f.path}` }))
        ].sort((a, b) => a.label.localeCompare(b.label));
        for (let i = 0; i < paths.length; i++) {
          const path = paths[i];
          const row = this.pathList.createDiv({ cls: "query-path-row" });
          const select = row.createEl("select", { cls: "query-path-select" });
          for (const item of items) {
            select.createEl("option", { text: item.label, value: item.value });
          }
          select.value = path.path;
          select.addEventListener("change", () => {
            path.path = select.value;
          });
          const toggleWrapper = row.createDiv({ cls: "query-path-toggle" });
          const toggle = toggleWrapper.createEl("input", {
            type: "checkbox",
            attr: { id: `qp-toggle-${i}` }
          });
          toggle.checked = path.enabled;
          toggle.addEventListener("change", () => {
            path.enabled = toggle.checked;
          });
          const deleteBtn = row.createEl("button", {
            cls: "query-path-delete",
            text: "\xD7"
          });
          deleteBtn.addEventListener("click", () => {
            paths.splice(i, 1);
            this.renderPathList();
          });
        }
      }
      addPath() {
        this.plugin.settings.queryPaths.push({
          id: crypto.randomUUID(),
          path: "",
          enabled: true
        });
        this.renderPathList();
      }
    };
  }
});

// calendar.ts
var calendar_exports = {};
__export(calendar_exports, {
  renderCalendar: () => renderCalendar
});
function renderCalendar(container, view) {
  renderToolbar(container, view);
  renderHeader(container, view);
  if (view.viewMode === "month") {
    renderWeekdayHeaders(container);
  }
  switch (view.viewMode) {
    case "month":
      renderMonthView(container, view);
      break;
    case "week":
      renderWeekView(container, view);
      break;
  }
}
function renderToolbar(container, view) {
  const toolbar = container.createDiv({ cls: "calendar-toolbar" });
  const modeGroup = toolbar.createDiv({ cls: "calendar-mode-group" });
  const modes = [
    { key: "month", label: "\u6708" },
    { key: "week", label: "\u5468" }
  ];
  for (const m of modes) {
    const btn = modeGroup.createEl("button", {
      cls: `calendar-mode-btn${view.viewMode === m.key ? " active" : ""}`,
      text: m.label
    });
    btn.addEventListener("click", () => {
      view.viewMode = m.key;
      view.render();
    });
  }
  const queryBtn = toolbar.createEl("button", {
    cls: "calendar-query-btn",
    text: "\u626B\u63CF\u8DEF\u5F84"
  });
  queryBtn.addEventListener("click", () => {
    const modal = new QueryPathModal(view.app, view.plugin, () => {
      view.loadTasks().then(() => view.render());
    });
    modal.open();
  });
  const colorBtn = toolbar.createEl("button", {
    cls: "calendar-color-rules-btn",
    text: "\u5206\u7C7B\u914D\u8272"
  });
  colorBtn.addEventListener("click", () => {
    const modal = new ColorRulesModal(view.app, view.plugin);
    modal.onClose = () => view.render();
    modal.open();
  });
  const filterBtn = toolbar.createEl("button", {
    cls: `calendar-filter-btn${view.hasActiveFilters ? " has-filters" : ""}`,
    text: "\u7B5B\u9009"
  });
  filterBtn.addEventListener("click", () => {
    const modal = new FilterModal(view.app, view.plugin);
    modal.onClose = () => view.render();
    modal.open();
  });
}
function renderHeader(container, view) {
  const header = container.createDiv({ cls: "calendar-header" });
  const prevBtn = header.createEl("button", { cls: "calendar-nav-btn", text: "\u2039" });
  prevBtn.addEventListener("click", () => {
    navigate(view, -1);
    view.render();
  });
  const title = header.createEl("span", { cls: "calendar-title" });
  title.setText(headerTitle(view));
  const nextBtn = header.createEl("button", { cls: "calendar-nav-btn", text: "\u203A" });
  nextBtn.addEventListener("click", () => {
    navigate(view, 1);
    view.render();
  });
  const todayBtn = header.createEl("button", { cls: "calendar-today-btn", text: "\u4ECA\u5929" });
  todayBtn.addEventListener("click", () => {
    view.currentDate = new Date();
    view.render();
  });
}
function navigate(view, direction) {
  switch (view.viewMode) {
    case "month":
      view.currentDate.setMonth(view.currentDate.getMonth() + direction);
      break;
    case "week":
      view.currentDate.setDate(view.currentDate.getDate() + direction * 7);
      break;
  }
}
function headerTitle(view) {
  const y = view.currentDate.getFullYear();
  const m = view.currentDate.getMonth();
  switch (view.viewMode) {
    case "month":
      return `${y}\u5E74${m + 1}\u6708`;
    case "week": {
      const mon = getWeekMonday(view.currentDate);
      const sun = new Date(mon);
      sun.setDate(sun.getDate() + 6);
      const fmt = (dt) => `${dt.getMonth() + 1}/${dt.getDate()}`;
      return `${y}\u5E74  ${fmt(mon)} \u2013 ${fmt(sun)}`;
    }
  }
  return "";
}
function renderWeekdayHeaders(container) {
  const row = container.createDiv({ cls: "calendar-weekdays" });
  for (const d of ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u65E5"]) {
    row.createDiv({ cls: "calendar-weekday", text: d });
  }
}
function renderMonthView(container, view) {
  const currentYear = view.currentDate.getFullYear();
  const currentMonth = view.currentDate.getMonth();
  const todayStr = formatDateStr2(new Date());
  const firstDayOfMonth = new Date(currentYear, currentMonth, 1);
  const lastDayOfMonth = new Date(currentYear, currentMonth + 1, 0);
  const jsWeekday = firstDayOfMonth.getDay();
  const startOffset = (jsWeekday + 6) % 7;
  const daysInMonth = lastDayOfMonth.getDate();
  const totalCells = startOffset + daysInMonth;
  const rows = Math.max(5, Math.ceil(totalCells / 7));
  const totalSlots = rows * 7;
  const allDays = [];
  if (startOffset > 0) {
    const prevMonth = currentMonth === 0 ? 11 : currentMonth - 1;
    const prevYear = currentMonth === 0 ? currentYear - 1 : currentYear;
    const prevMonthDays = new Date(prevYear, prevMonth + 1, 0).getDate();
    for (let i = 0; i < startOffset; i++) {
      const day = prevMonthDays - startOffset + i + 1;
      allDays.push({
        dateStr: `${prevYear}-${pad(prevMonth + 1)}-${pad(day)}`,
        dayNumber: day,
        isOtherMonth: true,
        isToday: false
      });
    }
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const dateStr = `${currentYear}-${pad(currentMonth + 1)}-${pad(day)}`;
    allDays.push({
      dateStr,
      dayNumber: day,
      isOtherMonth: false,
      isToday: dateStr === todayStr
    });
  }
  const usedCells = startOffset + daysInMonth;
  if (usedCells < totalSlots) {
    const nextMonth = currentMonth === 11 ? 0 : currentMonth + 1;
    const nextYear = currentMonth === 11 ? currentYear + 1 : currentYear;
    for (let day = 1; day <= totalSlots - usedCells; day++) {
      allDays.push({
        dateStr: `${nextYear}-${pad(nextMonth + 1)}-${pad(day)}`,
        dayNumber: day,
        isOtherMonth: true,
        isToday: false
      });
    }
  }
  const filteredTasks = view.allTasks.filter((t) => !isTaskFiltered(view, t));
  const weeks = [];
  for (let i = 0; i < allDays.length; i += 7) {
    weeks.push(allDays.slice(i, i + 7));
  }
  const grid = container.createDiv({ cls: "calendar-grid-month" });
  for (const week of weeks) {
    const weekRow = grid.createDiv({ cls: "calendar-week-row" });
    const weekStart = week[0].dateStr;
    const weekEnd = week[6].dateStr;
    const dateRow = weekRow.createDiv({ cls: "calendar-week-date-row" });
    for (const day of week) {
      const dateCell = dateRow.createDiv({
        cls: `calendar-week-date-cell${day.isOtherMonth ? " other-month" : ""}${day.isToday ? " today" : ""}`
      });
      dateCell.setText(String(day.dayNumber));
      setupContextMenu(dateCell, view, day.dateStr);
    }
    const barsOverlay = weekRow.createDiv({ cls: "calendar-week-bars-overlay" });
    const multiTasks = filteredTasks.filter((t) => {
      if (!isMultiDayTask(t))
        return false;
      return t.startDate <= weekEnd && t.dueDate >= weekStart;
    });
    const incompleteMulti = multiTasks.filter((t) => !t.completed).sort((a, b) => daySpan(b) - daySpan(a));
    const completedMulti = multiTasks.filter((t) => t.completed).sort((a, b) => daySpan(b) - daySpan(a));
    const incLanes = [];
    const compLanes = [];
    for (const task of incompleteMulti) {
      let placed = false;
      for (const lane of incLanes) {
        if (!lane.some((lt) => rangesOverlap(lt, task))) {
          lane.push(task);
          placed = true;
          break;
        }
      }
      if (!placed && incLanes.length < 4) {
        incLanes.push([task]);
      }
    }
    for (const task of completedMulti) {
      let placed = false;
      for (const lane of compLanes) {
        if (!lane.some((lt) => rangesOverlap(lt, task))) {
          lane.push(task);
          placed = true;
          break;
        }
      }
      if (!placed && compLanes.length < 4) {
        compLanes.push([task]);
      }
    }
    const lanes = [...incLanes, ...compLanes];
    const overlayHeight = Math.max(0, lanes.length * 28 + 4);
    barsOverlay.style.height = `${overlayHeight}px`;
    for (let li = 0; li < lanes.length; li++) {
      for (const task of lanes[li]) {
        let startCol = week.findIndex((d) => d.dateStr === task.startDate);
        let endCol = week.findIndex((d) => d.dateStr === task.dueDate);
        if (startCol === -1)
          startCol = 0;
        if (endCol === -1)
          endCol = 6;
        const span = endCol - startCol + 1;
        const leftPct = startCol / 7 * 100;
        const widthPct = span / 7 * 100;
        const bar = barsOverlay.createDiv({ cls: "month-multi-bar" });
        if (task.completed)
          bar.addClass("completed");
        bar.style.left = `calc(${leftPct}% + 1px)`;
        bar.style.width = `calc(${widthPct}% - 2px)`;
        bar.style.top = `${li * 28 + 2}px`;
        const startsBeforeWeek = task.startDate < weekStart;
        const endsAfterWeek = task.dueDate > weekEnd;
        if (startsBeforeWeek)
          bar.addClass("continues-left");
        if (endsAfterWeek)
          bar.addClass("continues-right");
        const blockColor = view.getBlockTintColor(task);
        const barColors = view.getMatchingBarColors(task);
        if (blockColor) {
          bar.style.backgroundColor = blockColor;
          bar.addClass("block-tint");
        }
        if (barColors.length > 0) {
          const stripe = bar.createDiv({ cls: "month-bar-stripe" });
          stripe.style.backgroundColor = barColors[0];
        }
        bar.createSpan({ cls: "month-bar-text", text: task.description });
        bar.addEventListener("click", (e) => {
          if (bar.dataset.ignoreClick)
            return;
          if (e.target.closest(".month-bar-hit-left, .month-bar-hit-right"))
            return;
          view.openTaskFile(task);
        });
        const leftHit = bar.createDiv({ cls: "month-bar-hit-left" });
        leftHit.setAttr("title", "\u8C03\u6574\u8D77\u59CB\u65E5\u671F");
        setupBarResize(leftHit, task, "start", weekRow, view);
        const rightHit = bar.createDiv({ cls: "month-bar-hit-right" });
        rightHit.setAttr("title", "\u8C03\u6574\u7EC8\u6B62\u65E5\u671F");
        setupBarResize(rightHit, task, "due", weekRow, view);
      }
    }
    for (const day of week) {
      const dayEl = weekRow.createDiv({
        cls: `calendar-day-cell${day.isOtherMonth ? " other-month" : ""}${day.isToday ? " today" : ""}`
      });
      const dayTasks = filteredTasks.filter((t) => {
        if (!t.startDate)
          return false;
        const end = t.dueDate || t.startDate;
        return day.dateStr >= t.startDate && day.dateStr <= end;
      });
      const multiBarCount = lanes.filter(
        (lane) => lane.some((t) => {
          const end = t.dueDate || t.startDate;
          return day.dateStr >= t.startDate && day.dateStr <= end;
        })
      ).length;
      const maxVisible = 5;
      const availableSlots = Math.max(0, maxVisible - multiBarCount);
      const overflowMulti = dayTasks.filter(
        (t) => isMultiDayTask(t) && !lanes.some((lane) => lane.includes(t))
      );
      const singleDayTasks = dayTasks.filter((t) => !isMultiDayTask(t));
      const allCards = [...overflowMulti, ...singleDayTasks];
      allCards.sort((a, b) => (a.completed ? 1 : 0) - (b.completed ? 1 : 0));
      const visibleCards = allCards.slice(0, availableSlots);
      const hiddenCount = allCards.length - availableSlots;
      const tasksContainer = dayEl.createDiv({ cls: "calendar-notes" });
      for (const task of visibleCards) {
        tasksContainer.appendChild(
          createTaskCard(task, view, "month", weekRow)
        );
      }
      if (hiddenCount > 0) {
        const overflowBtn = dayEl.createDiv({ cls: "task-overflow-btn" });
        overflowBtn.setText(`\u8FD8\u6709 ${hiddenCount} \u4E2A`);
        overflowBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          showTaskPopup(dayEl, day.dateStr, dayTasks, view);
        });
      }
    }
  }
}
function renderWeekView(container, view) {
  const mon = getWeekMonday(view.currentDate);
  const grid = container.createDiv({ cls: "calendar-week-grid" });
  const todayStr = formatDateStr2(new Date());
  const dayNames = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u65E5"];
  for (let i = 0; i < 7; i++) {
    const d = new Date(mon);
    d.setDate(d.getDate() + i);
    const dateStr = formatDateStr2(d);
    const tasks = view.getTasksForDate(dateStr);
    const isToday = dateStr === todayStr;
    const col = grid.createDiv({ cls: `calendar-week-col${isToday ? " today" : ""}` });
    const colHeader = col.createDiv({ cls: "calendar-week-col-header" });
    colHeader.createSpan({ cls: "calendar-week-col-day", text: dayNames[i] });
    colHeader.createSpan({ cls: "calendar-week-col-date", text: `${d.getMonth() + 1}/${d.getDate()}` });
    setupContextMenu(col, view, dateStr);
    const tasksContainer = col.createDiv({ cls: "calendar-week-notes" });
    for (const task of tasks) {
      tasksContainer.appendChild(createTaskCard(task, view, "week"));
    }
  }
}
function createTaskCard(task, view, viewContext, weekRow) {
  const barColors = view.getMatchingBarColors(task);
  const blockColor = view.getBlockTintColor(task);
  const cls = ["calendar-note"];
  if (task.completed)
    cls.push("completed");
  if (isMultiDayTask(task))
    cls.push("multi-day-task");
  const card = createDiv({ cls: cls.join(" ") });
  card.setAttr("data-task-id", task.id);
  if (blockColor) {
    card.style.backgroundColor = blockColor;
    card.addClass("block-tint");
  }
  if (barColors.length > 0) {
    const bars = card.createDiv({ cls: "calendar-note-bars" });
    for (const c of barColors) {
      bars.createDiv({ cls: "calendar-note-bar", attr: { style: `background-color:${c}` } });
    }
  }
  card.createSpan({ cls: "calendar-note-text", text: task.description });
  if (task.priority !== "none") {
    card.createSpan({
      cls: `task-priority task-priority-${task.priority}`,
      text: getPriorityEmoji(task.priority)
    });
  }
  if (viewContext !== "month" && task.tags.length > 0) {
    const tagsEl = card.createDiv({ cls: "task-tags" });
    for (const tag of task.tags.slice(0, 3)) {
      tagsEl.createSpan({ cls: "task-tag", text: `#${tag}` });
    }
  }
  if (viewContext !== "month" && isMultiDayTask(task)) {
    card.createDiv({ cls: "task-date-range", text: `${task.startDate} \u2192 ${task.dueDate}` });
  }
  card.addEventListener("click", () => {
    if (card.dataset.ignoreClick)
      return;
    view.openTaskFile(task);
  });
  if (viewContext === "month" && weekRow) {
    const leftHit = card.createDiv({ cls: "card-hit-left" });
    leftHit.setAttr("title", "\u8C03\u6574\u8D77\u59CB\u65E5\u671F");
    setupBarResize(leftHit, task, "start", weekRow, view);
    const rightHit = card.createDiv({ cls: "card-hit-right" });
    rightHit.setAttr("title", "\u8C03\u6574\u7EC8\u6B62\u65E5\u671F");
    setupBarResize(rightHit, task, "due", weekRow, view);
  }
  return card;
}
function getPriorityEmoji(priority) {
  switch (priority) {
    case "high":
      return "\u2757\u2757\u2757";
    case "medium":
      return "\u2757\u2757";
    case "low":
      return "\u2757";
    default:
      return "";
  }
}
function createDiv(opts) {
  const d = document.createElement("div");
  d.className = opts.cls;
  return d;
}
function setupBarResize(hitEl, task, field, weekRow, view) {
  hitEl.addEventListener("mousedown", (e) => {
    e.preventDefault();
    e.stopPropagation();
    const rowRect = weekRow.getBoundingClientRect();
    const dayWidth = rowRect.width / 7;
    const startX = e.clientX;
    const otherDate = field === "start" ? task.dueDate || task.startDate : task.startDate;
    const fixedDate = field === "start" ? task.startDate : task.dueDate || task.startDate;
    const parentBar = hitEl.closest(".month-multi-bar, .calendar-note");
    if (parentBar) {
      parentBar.dataset.ignoreClick = "true";
    }
    const tooltip = document.body.createDiv({ cls: "resize-tooltip" });
    tooltip.setText(fixedDate);
    updateTooltipPos(tooltip, e.clientX, e.clientY);
    const onMouseMove = (e2) => {
      const deltaX = e2.clientX - startX;
      const deltaDays = Math.round(deltaX / Math.max(dayWidth, 20));
      const newDate = addDays2(fixedDate, deltaDays);
      tooltip.setText(newDate);
      updateTooltipPos(tooltip, e2.clientX, e2.clientY);
    };
    const onMouseUp = async (e2) => {
      const deltaX = e2.clientX - startX;
      const deltaDays = Math.round(deltaX / Math.max(dayWidth, 20));
      const newDate = addDays2(fixedDate, deltaDays);
      tooltip.remove();
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      if (parentBar) {
        setTimeout(() => {
          delete parentBar.dataset.ignoreClick;
        }, 100);
      }
      if (newDate === fixedDate)
        return;
      if (field === "start") {
        if (newDate > otherDate) {
          await view.updateTaskDate(task, otherDate, otherDate);
        } else {
          await view.updateTaskDate(task, newDate, otherDate);
        }
      } else {
        if (newDate < otherDate) {
          await view.updateTaskDate(task, otherDate, otherDate);
        } else {
          await view.updateTaskDate(task, otherDate, newDate);
        }
      }
    };
    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
  });
}
function updateTooltipPos(el, x, y) {
  el.style.left = `${x}px`;
  el.style.top = `${y - 36}px`;
}
function setupContextMenu(el, view, dateStr) {
  el.addEventListener("contextmenu", (e) => {
    e.preventDefault();
    const menu = new import_obsidian5.Menu();
    menu.addItem((item) => {
      item.setTitle("\u65B0\u5EFA\u4EFB\u52A1").setIcon("file-plus").onClick(() => showCreateTaskModal(view.app, view, dateStr));
    });
    menu.showAtPosition({ x: e.clientX, y: e.clientY });
  });
}
function showCreateTaskModal(app, view, dateStr) {
  const modalEl = document.body.createDiv({ cls: "calendar-create-modal" });
  modalEl.createEl("div", { cls: "calendar-create-title", text: `\u65B0\u5EFA\u4EFB\u52A1 \u2014 ${dateStr}` });
  const input = modalEl.createEl("input", {
    cls: "calendar-create-input",
    type: "text",
    attr: { placeholder: "\u4EFB\u52A1\u63CF\u8FF0" }
  });
  input.focus();
  const footer = modalEl.createDiv({ cls: "calendar-create-footer" });
  const cancelBtn = footer.createEl("button", { text: "\u53D6\u6D88" });
  cancelBtn.addEventListener("click", () => modalEl.remove());
  const okBtn = footer.createEl("button", { cls: "mod-cta", text: "\u521B\u5EFA" });
  okBtn.addEventListener("click", async () => {
    const title = input.value.trim();
    if (!title)
      return;
    modalEl.remove();
    await createTaskForDate(app, view, dateStr, title);
  });
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter") {
      const title = input.value.trim();
      if (!title)
        return;
      modalEl.remove();
      createTaskForDate(app, view, dateStr, title);
    }
  });
}
async function createTaskForDate(app, view, dateStr, description) {
  const paths = view.plugin.settings.queryPaths.filter((p) => p.enabled);
  const folder = paths.length > 0 ? paths[0].path : "";
  const fileName = `Tasks ${dateStr}`;
  let fullPath = folder ? `${folder}/${fileName}.md` : `${fileName}.md`;
  let file = app.vault.getAbstractFileByPath(fullPath);
  if (!file) {
    const content = `- [ ] ${description} \u{1F6EB} ${dateStr}
`;
    await app.vault.create(fullPath, content);
  } else if (file instanceof import_obsidian5.TFile) {
    const existing = await app.vault.read(file);
    const newContent = existing + `
- [ ] ${description} \u{1F6EB} ${dateStr}`;
    await app.vault.modify(file, newContent);
  }
  await view.loadTasks();
  view.render();
}
function showTaskPopup(anchorEl, dateStr, tasks, view) {
  document.querySelectorAll(".task-day-popup").forEach((el) => el.remove());
  const popup = document.body.createDiv({ cls: "task-day-popup" });
  const rect = anchorEl.getBoundingClientRect();
  let left = rect.right + 4;
  let top = rect.top;
  const popupWidth = 260;
  const popupHeight = Math.min(400, tasks.length * 44 + 60);
  if (left + popupWidth > window.innerWidth - 16)
    left = rect.left - popupWidth - 4;
  if (top + popupHeight > window.innerHeight - 16)
    top = window.innerHeight - popupHeight - 16;
  if (top < 16)
    top = 16;
  popup.style.left = `${left}px`;
  popup.style.top = `${top}px`;
  const header = popup.createDiv({ cls: "task-popup-header" });
  header.setText(`${dateStr} \u2014 ${tasks.length} \u4E2A\u4EFB\u52A1`);
  const list = popup.createDiv({ cls: "task-popup-list" });
  for (const task of tasks) {
    const item = list.createDiv({ cls: "task-popup-item" });
    const status = item.createDiv({ cls: "task-popup-status" });
    status.setText(task.completed ? "\u2611" : "\u2610");
    if (task.completed)
      status.addClass("completed");
    const info = item.createDiv({ cls: "task-popup-info" });
    info.createDiv({ cls: "task-popup-desc", text: task.description });
    const meta = info.createDiv({ cls: "task-popup-meta" });
    if (task.priority !== "none") {
      meta.createSpan({ cls: `task-popup-priority task-priority-${task.priority}`, text: getPriorityEmoji(task.priority) });
    }
    for (const tag of task.tags.slice(0, 3)) {
      meta.createSpan({ cls: "task-popup-tag", text: `#${tag}` });
    }
    if (isMultiDayTask(task)) {
      meta.createSpan({ cls: "task-popup-range", text: `${task.startDate}\u2192${task.dueDate}` });
    }
    item.addEventListener("click", () => {
      view.openTaskFile(task);
      popup.remove();
    });
  }
  const closeHandler = (e) => {
    if (!popup.contains(e.target)) {
      popup.remove();
      document.removeEventListener("click", closeHandler);
    }
  };
  setTimeout(() => document.addEventListener("click", closeHandler), 0);
}
function isTaskFiltered(view, task) {
  const filters = view.plugin.settings.filterRules.filter(
    (r) => r.enabled && r.keyword.trim()
  );
  return filters.some((f) => {
    const kw = f.keyword.toLowerCase();
    switch (f.property) {
      case "tags":
        return task.tags.some((t) => t.toLowerCase().includes(kw));
      case "priority":
        return task.priority.toLowerCase().includes(kw);
      case "description":
        return task.description.toLowerCase().includes(kw);
    }
    return false;
  });
}
function rangesOverlap(a, b) {
  const aStart = a.startDate;
  const aEnd = a.dueDate || a.startDate;
  const bStart = b.startDate;
  const bEnd = b.dueDate || b.startDate;
  return aStart <= bEnd && bStart <= aEnd;
}
function daySpan(task) {
  if (!task.startDate || !task.dueDate)
    return 1;
  const s = new Date(task.startDate);
  const e = new Date(task.dueDate);
  return Math.round((e.getTime() - s.getTime()) / (1e3 * 60 * 60 * 24)) + 1;
}
function addDays2(dateStr, days) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return formatDateStr2(d);
}
function formatDateStr2(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function pad(n) {
  return String(n).padStart(2, "0");
}
function getWeekMonday(date) {
  const d = new Date(date);
  const day = d.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  d.setDate(d.getDate() + diff);
  d.setHours(0, 0, 0, 0);
  return d;
}
var import_obsidian5;
var init_calendar = __esm({
  "calendar.ts"() {
    import_obsidian5 = require("obsidian");
    init_colorRulesModal();
    init_filterModal();
    init_queryPathModal();
    init_taskParser();
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// view.ts
var import_obsidian6 = require("obsidian");
init_taskParser();
var VIEW_TYPE_CALENDAR = "task-calendar-view";
var TaskCalendarView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this._renderTimeout = null;
    this._projectScroll = null;
    this._allTasks = [];
    this.plugin = plugin;
    this.currentDate = new Date();
    this.viewMode = "month";
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "Task Calendar";
  }
  getIcon() {
    return "calendar";
  }
  async onOpen() {
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (file.extension === "md") {
          this.scheduleRender();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          this.scheduleRender();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          this.scheduleRender();
        }
      })
    );
    await this.loadTasks();
    this.render();
  }
  async onClose() {
    this.containerEl.empty();
  }
  scheduleRender() {
    if (this._renderTimeout) {
      window.clearTimeout(this._renderTimeout);
    }
    this._renderTimeout = window.setTimeout(async () => {
      this._renderTimeout = null;
      await this.loadTasks();
      this.render();
    }, 250);
  }
  async loadTasks() {
    this._allTasks = await getAllTasks(
      this.app,
      this.plugin.settings.queryPaths
    );
  }
  render() {
    if (this._renderTimeout) {
      window.clearTimeout(this._renderTimeout);
      this._renderTimeout = null;
    }
    this.containerEl.empty();
    const container = this.containerEl.createDiv({ cls: "calendar-view-container" });
    const { renderCalendar: renderCalendar2 } = (init_calendar(), __toCommonJS(calendar_exports));
    renderCalendar2(container, this);
  }
  get allTasks() {
    return this._allTasks;
  }
  get hasActiveFilters() {
    return this.plugin.settings.filterRules.some(
      (r) => r.enabled && r.keyword.trim()
    );
  }
  getEnabledColorRules() {
    return this.plugin.settings.colorRules.filter(
      (r) => r.enabled && r.keyword.trim()
    );
  }
  getEnabledFilterRules() {
    return this.plugin.settings.filterRules.filter(
      (r) => r.enabled && r.keyword.trim()
    );
  }
  // ── Filter matching ──────────────────────────────────────
  isTaskFiltered(task) {
    const filters = this.getEnabledFilterRules();
    return filters.some((f) => this.taskMatchesFilter(task, f));
  }
  taskMatchesFilter(task, filter) {
    const keyword = filter.keyword.toLowerCase();
    switch (filter.property) {
      case "tags":
        return task.tags.some((t) => t.toLowerCase().includes(keyword));
      case "priority":
        return task.priority.toLowerCase().includes(keyword);
      case "description":
        return task.description.toLowerCase().includes(keyword);
    }
    return false;
  }
  // ── Color matching: bar mode ───────────────────────────
  getMatchingBarColors(task) {
    const rules = this.getEnabledColorRules().filter((r) => r.displayMode === "bar");
    const colors = [];
    for (const rule of rules) {
      if (this.taskMatchesColorRule(task, rule)) {
        colors.push(rule.color);
        if (colors.length >= 3)
          break;
      }
    }
    return colors;
  }
  // ── Color matching: block mode ─────────────────────────
  getBlockTintColor(task) {
    const rules = this.getEnabledColorRules().filter((r) => r.displayMode === "block");
    for (const rule of rules) {
      if (this.taskMatchesColorRule(task, rule)) {
        return rule.color;
      }
    }
    return null;
  }
  taskMatchesColorRule(task, rule) {
    const keyword = rule.keyword.toLowerCase();
    switch (rule.property) {
      case "tags":
        return task.tags.some((t) => t.toLowerCase() === keyword);
      case "priority":
        return task.priority.toLowerCase() === keyword;
      case "description":
        return task.description.toLowerCase().includes(keyword);
    }
    return false;
  }
  // ── Sort priority ──────────────────────────────────────
  getTaskSortPriority(task) {
    const rules = this.getEnabledColorRules();
    for (let i = 0; i < rules.length; i++) {
      if (this.taskMatchesColorRule(task, rules[i]))
        return i;
    }
    return rules.length;
  }
  // ── Tasks grouping ─────────────────────────────────────
  getTasksWithDate() {
    const filtered = this._allTasks.filter((t) => !this.isTaskFiltered(t));
    const byDate = groupTasksByDate(filtered);
    for (const [dateStr, tasks] of byDate) {
      tasks.sort((a, b) => {
        const pa = this.getTaskSortPriority(a);
        const pb = this.getTaskSortPriority(b);
        if (pa !== pb)
          return pa - pb;
        return a.description.localeCompare(b.description);
      });
    }
    return byDate;
  }
  getTasksForDate(dateStr) {
    const filtered = this._allTasks.filter((t) => !this.isTaskFiltered(t));
    return filtered.filter((t) => {
      if (!t.startDate)
        return false;
      const end = t.dueDate || t.startDate;
      return dateStr >= t.startDate && dateStr <= end;
    });
  }
  // ── Project data ───────────────────────────────────────
  getProjectsData() {
    const projects = this.plugin.settings.projects.filter((p) => p.enabled);
    const filteredTasks = this._allTasks.filter((t) => !this.isTaskFiltered(t));
    return projects.map((p) => {
      let tasks = [];
      if (p.filterType === "path") {
        const prefix = p.filterValue ? p.filterValue + "/" : "";
        tasks = filteredTasks.filter((t) => t.filePath.startsWith(prefix));
      } else if (p.filterType === "tag") {
        tasks = filteredTasks.filter(
          (t) => t.tags.some(
            (tag) => tag.toLowerCase() === p.filterValue.toLowerCase()
          )
        );
      }
      const total = tasks.length;
      const hit = tasks.filter((t) => t.completed).length;
      const progress = total > 0 ? Math.round(hit / total * 100) : 0;
      const tasksByDate = /* @__PURE__ */ new Map();
      for (const t of tasks) {
        if (!t.startDate)
          continue;
        const start = t.startDate;
        const end = t.dueDate || start;
        const d = new Date(start);
        const endD = new Date(end);
        while (d <= endD) {
          const ds = formatDateStr3(d);
          if (!tasksByDate.has(ds))
            tasksByDate.set(ds, []);
          tasksByDate.get(ds).push(t);
          d.setDate(d.getDate() + 1);
        }
      }
      return { project: p, total, hit, progress, tasksByDate, tasks };
    });
  }
  // ── Date update ────────────────────────────────────────
  async updateTaskDate(task, newStartDate, newDueDate) {
    await updateTaskDates(this.app, task, newStartDate, newDueDate);
    await this.loadTasks();
    this.render();
  }
  async shiftTask(task, days) {
    const shifted = shiftTaskDates(task, days);
    await updateTaskDates(this.app, task, shifted.startDate, shifted.dueDate);
    await this.loadTasks();
    this.render();
  }
  // ── Open file at line ──────────────────────────────────
  async openTaskFile(task) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian6.TFile))
      return;
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.openFile(file);
    const view = leaf.view;
    if (view && "editor" in view) {
      const editor = view.editor;
      if (editor && typeof editor.setCursor === "function") {
        editor.setCursor({ line: task.lineNumber, ch: 0 });
      }
    }
  }
};
function formatDateStr3(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// main.ts
init_settings();
var TaskCalendarPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_CALENDAR,
      (leaf) => new TaskCalendarView(leaf, this)
    );
    this.addRibbonIcon("calendar", "Open Task Calendar", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-task-calendar-view",
      name: "Open Task Calendar",
      callback: () => {
        this.activateView();
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CALENDAR);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await (leaf == null ? void 0 : leaf.setViewState({ type: VIEW_TYPE_CALENDAR, active: true }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
